export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';

export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const LOG_OUT = 'LOG_OUT';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const LOADING_FILE = 'LOADING_FILE';
export const SUCCESSFUL_FILE_UPLOAD = 'SUCCESSFUL_FILE_UPLOAD';
export const ERROR_FILE_UPLOAD = 'ERROR_FILE_UPLOAD';

export const SUCCESSFUL_CREATE_LINK = 'SUCCESSFUL_CREATE_LINK';
export const ERROR_CREATE_LINK = 'ERROR_CREATE_LINK';

export const CLEAN_STATE = 'CLEAN_STATE';

export const ADD_PASSWORD = 'ADD_PASSWORD';


